name: Model Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Debug Repository Structure
      run: |
        echo "Current directory contents:"
        pwd
        ls -R
    
    - name: Python and Environment Check
      run: |
        python --version
        pip --version
        which python
        python -m site
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential
    
    - name: Verify Requirements File
      run: |
        echo "Contents of requirements.txt:"
        cat requirements.txt || echo "requirements.txt not found"
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --verbose -r requirements.txt || echo "Dependency installation failed"
        pip install pytest pytest-cov
    
    - name: List Installed Packages
      run: pip list
    
    - name: Run Tests with Verbose Output
      run: |
        python -m pytest tests/ -v --cov=. --cov-report=xml || echo "Test execution failed"