name: Model Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: List contents of repository
      run: |
        pwd
        ls -la
    
    - name: Check Python and pip versions
      run: |
        python --version
        pip --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
        pip install pytest pytest-cov
    
    - name: List installed packages
      run: pip list
    
    - name: Run tests
      run: |
        if [ -d tests ]; then 
          pytest tests/ --cov=. --cov-report=xml
        else
          echo "No tests directory found"
        fi